---
title: "proyecto"
output: html_document
date: '2022-06-28'
---

```{r warning=FALSE}
library(haven)
library(foreign)
library(nortest)#Kolmogorov
library(readr) #Leer archivos
#library(tidyverse) #Manipular la data
library(lubridate) #Manipular las fechas
library(aweek) #Manipular las fechas
library(dplyr)
library(modeest)
```

# Lecture and Filtering of the data base

```{r}
# Read csv file
df <- read.csv("violence_clean.csv")

# Storing only relevant variables
df <- df %>% dplyr::select(`reporting_center`, `newcase`,`year`, `crime_years`, `crime_region`, `crime_urban`, `crime_femicide_attemp`, `crime_violence_type`, `verbal_assault`, `victim_age`, `victim_children`, `victim_children_groups`, `victim_language`, `victim_civil_status`, `victim_education`, `victim_job_status`, `victim_discapacity`, `victim_filesacomplaint`, `sex_harassment`, `sex_rape`, `verbal_assault`, `thread_children`, `physical_kicks`, `physical_punches`, `physical_hairpull`, `victim_children_groups`, `treatment_psycological`, `treatment_psyquiatric`, `treatment_medic`, `bond_family_d`, `bond_family_d`, `bond_coworkers`, `bond_neighbor`, `bond_friends`, `bond_partner`, `agressor_age`, `agressor_age_group`, `agressor_gender`, `agressor_education`, `agressor_education`, `agressor_job_status`, `agressor_foreign`)
```

```{r}
# Dep distribution used for the research
dep_coastal <- c("Moquegua", "Ica", "Lima", "Arequipa", "Tacna", "Lambayeque", "Callao", "Áncash", "La Libertad", "Piura", "Tumbes", "Callao")
dep_highland <-c("Ayacucho", "Junín", "Cusco", "Apurímac", "San Martín", "Cajamarca", "Huancavelica", "Huánuco", "Puno")
dep_jungle <- c("Amazonas", "Pasco", "Madre de Dios", "Loreto2", "Ucayali")
```


```{r}
#add a column for dep
df['dep'] = NaN

df<- df %>%  
  mutate(dep = ifelse(crime_region %in% dep_coastal, 'coastal', 
             ifelse(crime_region %in% dep_highland, 'highland', 'jungle')))
```

```{r}
# Filtered data frames
df_coastal <- df %>% filter(crime_region %in% dep_coastal)
df_highland <- df %>% filter(crime_region %in% dep_highland)
df_jungle <- df %>% filter(crime_region %in% dep_jungle)
regions <- c(df_coastal, df_highland, df_jungle)
```


```{r}
#Dimension del data frame (filas y columnas)
dim(df) 

# Nos muestra las primeras 15 observaciones
head(df, n = 15) 
```

# descriptive analysis





```{r}
analyze_single_var <- function(x){
  # cat("MEAN: ", mean(x, na.rm = TRUE), '\n')
  # cat("MEDIAN: ", median(x, na.rm = TRUE), '\n')
  # cat("MODE: ", mfv(x, na_rm = TRUE), '\n')
  # sub(''substitute(x))

  summary(x)
}
```

Analizadno las variables
```{r}
# Original dfs metrics
cat('victim age\n')
analyze_single_var( df$victim_age)

cat('crime years\n')
analyze_single_var(df$crime_years)

cat('victim children\n')
analyze_single_var(df$victim_children)
```


```{r}
table(df$dep) / nrow(df) * 100
```




```{r}
ggplot(data = df, aes(x = dep, y = victim_age)) +
       stat_boxplot(geom = "errorbar",      # Error bars
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE",       # Box color
                    outlier.colour = "red", # Outliers color
                    alpha = 0.9) +          # Box color transparency
       # ggtitle("Boxplot with vector") + # Plot title
       xlab("") +   # X-axis label
       ylab("Edad de la victima") 
```



```{r}
ggplot(data = df, aes(x = dep, y = agressor_age)) +
       stat_boxplot(geom = "errorbar",      # Error bars
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE",       # Box color
                    outlier.colour = "red", # Outliers color
                    alpha = 0.9) +          # Box color transparency
       # ggtitle("Boxplot with vector") + # Plot title
       xlab("") +   # X-axis label
       ylab("Agresor age") 
```

```{r}
ggplot(data = df, aes(x = dep, y = crime_years)) +
       stat_boxplot(geom = "errorbar",      # Error bars
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE",       # Box color
                    outlier.colour = "red", # Outliers color
                    alpha = 0.9) +          # Box color transparency
       # ggtitle("Boxplot with vector") + # Plot title
       xlab("") +   # X-axis label
       ylab("Crime yeras") 
```


```{r}
ggplot(data = df, aes(x = dep, y = victim_children)) +
       stat_boxplot(geom = "errorbar",      # Error bars
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE",       # Box color
                    outlier.colour = "red", # Outliers color
                    alpha = 0.9) +          # Box color transparency
       # ggtitle("Boxplot with vector") + # Plot title
       xlab("") +   # X-axis label
       ylab("Numero de Hijos") 
```

Pruebas de normalidad

```{r, warning=FALSE}
analyze_dist <- function(x, threshold_p = 0.05, threshold_cv = 0.5){
  p_value <- as.numeric(lillie.test(x)[2])
  is_normal <- FALSE
  if(p_value > threshold_p){
    is_normal <- TRUE
  }
  cv <- sd(x, na.rm = TRUE)/mean(x, na.rm = TRUE)
  is_parametric <- FALSE
  if(cv < threshold_cv){
    is_parametric <- TRUE
  }
  return(list("has_normal_dist"=is_normal,"has_parametric_dist"=is_parametric,"p_value"= p_value,"cv"=cv))
}

victim_age_dist <- analyze_dist(df$victim_age)
print(victim_age_dist)
```


